name: Run Daily Check-In

on:
  schedule:
    - cron: "0 */6 * * *" # Schedule to run every 6 hours
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Save CHECKIN_CONFIG to config.json
        run: |
          echo -n "${{ secrets.CHECKIN_CONFIG }}" | base64 -d > config.json
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
        working-directory: ${{ github.workspace }}
      - name: Run script
        run: |
          python -OO main.py
        working-directory: ${{ github.workspace }}
